---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: splunk-otel-agent
users:
- system:serviceaccount:splunk-otel-operator-system:splunk-otel-account
priority: 10
allowHostNetwork: true 
allowHostPorts: true
allowHostPID: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowPrivilegedContainer: false
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- secret
# Allow podman/crio socket and /proc access
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    user: "system_u"
    role: "system_r"
    type: "spc_t"
    level: "s0"
allowedFlexVolumes: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
requiredDropCapabilities: []
